name: Machine Learning Client CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y portaudio19-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with Pylint
      run: |
        pip install pytest pylint
        pylint **/*.py
    # - name: Test with pytest
    #   run: |
    #    cd machine-learning-client
    #    pytest tests.py