name: Web App CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y portaudio19-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with Pylint
      run: |
        pip install pylint pytest
        pylint **/*.py
    # - name: Test with pytest
    #   run: |
    #    cd web-app
    #    pytest tests.py

  build-and-push:
      needs: build-and-test
      runs-on: ubuntu-latest
      if: github.event_name == 'push'
      steps:
        - uses: actions/checkout@v2
        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build and push Docker image for machine-learning-client
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile.mlc
            push: true
            tags: zijiezhao/project4-machine-learning-client:latest
        - name: Build and push Docker image for web-app
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile.web
            push: true
            tags: zijiezhao/project4-web-app:latest

